  development :
    cloud_name: "memee"
    api_key: "713638533155223"
    api_secret: "-_q0w5x0zx70BCBVeTuWAmPOjJY"
    secure : true

  production :
    cloud_name : "memee"
    api_key : "713638533155223"
    api_secret: "-_q0w5x0zx70BCBVeTuWAmPOjJY"
    secure : true