# database.yml
development:
  adapter: postgresql
  encoding: unicode
  database: app_development
  username: nabeeha
  password: <%= ENV['DB_PASSWORD'] %>
  host: 35.244.25.128
  port: 5432
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: test_development
  username: nabeeha
  password: <%= ENV['DB_PASSWORD'] %>
  host: 35.244.25.128
  port: 5432
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: app_production
  username: nabeeha
  password: <%= ENV['DB_PASSWORD'] %>
  host: 35.244.25.128
  port: 5432
  pool: 5
  timeout: 5000


staging:
  encoding: unicode
  pool: 5
  adapter: postgresql
  host: localhost
  username: deploy
  password: admin123
  database: memee-staging
