name: CI/CD Pipeline for Ruby on Rails on GCP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: nabeeha
          POSTGRES_PASSWORD: ${{ secrets.PG_DB_PASSWORD }}
          POSTGRES_DB: app_development
        options: >-
          --health-cmd="pg_isready -U nabeeha"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0 # or any version your project uses

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Debug Step: Check if DB_PASSWORD is set correctly
      - name: Debug Database Environment Variables
        run: |
          echo "Checking database environment variables..."
          echo "POSTGRES_USER: $POSTGRES_USER"
          echo "POSTGRES_PASSWORD: $POSTGRES_PASSWORD"
          echo "POSTGRES_DB: $POSTGRES_DB"
        env:
          POSTGRES_USER: nabeeha
          POSTGRES_PASSWORD: ${{ secrets.PG_DB_PASSWORD }}
          POSTGRES_DB: app_development
      
      - name: Test PostgreSQL Connection
        run: |
          pg_isready -h 35.244.25.128 -U nabeeha -p 5432
          
      - name: Debug DB_PASSWORD Directly
        run: |
           echo "DB_PASSWORD is set to: ${{ secrets.PG_DB_PASSWORD }}"

      - name: Set up Database
        run: |
          rails db:create db:migrate
        env:
          RAILS_ENV: development
          POSTGRES_USER: nabeeha
          POSTGRES_PASSWORD: ${{ secrets.PG_DB_PASSWORD }}
          POSTGRES_DB: app_development


  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Debug Step: Check GCP Credentials
      - name: Debug GCP Credentials
        run: |
          echo "Debugging GCP credentials..."
          echo "GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ror-deployment
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Deploy to GCP
        run: |
          gcloud app deploy
