name: Build and Deploy to Cloud Run
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > gcp_credentials.json
          mkdir -p app/config
          mv gcp_credentials.json app/config/gcp_credentials.json

      - name: View GCP Credentials
        run: |
          cat app/config/gcp_credentials.json

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ror-deployment
          export_default_credentials: true

      - name: Configure Docker with Google Cloud auth
        run: |
          gcloud auth configure-docker

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u nabeehadev --password-stdin

      - name: Build Docker image
        run: |
          docker build -t nabeehadev/rorapp:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push nabeehadev/rorapp:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy rorapp \
            --image docker.io/nabeehadev/rorapp:latest \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated \
            --update-env-vars BUCKET_NAME=ror-deployment-gcp,DB_CONNECTION_NAME=ror-deployment:asia-south1:ror-database-gcp
