name: Build and Deploy RoR App to Google Artifact Registry

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ror-gcp  
      PROJECT_ID: ror_deployment
      REGION: asia-south1
      REPOSITORY_NAME: ror-gcp-docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: $PROJECT_ID
          export_default_credentials: true

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Push Docker image to Artifact Registry
        run: |
          docker tag $IMAGE_NAME:latest $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:latest
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:latest
